import {
  Crown,
  Palette,
  Lightbulb,
  Search,
  Brain,
  Keyboard,
  Hand,
  Heart,
  Sparkles,
  Layers,
  Star,
  NotebookPen,
  FolderOpen,
  Target,
  UserRound,
  CircleCheck,
  BookOpen,
  CalendarDays,
  Hospital,
  PartyPopper,
  ShieldCheck,
  TriangleAlert,
  Trash2,
  SprayCan,
  Tag,
  Scale,
  Glasses,
  Ban,
  Recycle,
  ShowerHead,
  Wind,
  Archive,
  Flame,
  LockKeyhole,
  Thermometer,
  Megaphone,
  IdCard,
  UsersRound,
  Scissors,
  Droplets,
  Moon,
  Apple,
  Eye,
  HeartPulse,
  Handshake,
  PhoneOff,
  Coffee,
  PenLine,
  Utensils,
  AlarmClock,
  RefreshCw,
  Zap,
  Package,
  GraduationCap,
  Smile,
  Meh,
  Pause,
  Play,
  ArrowUpRight,
} from 'lucide-react';
const icons = {
  Crown,
  Palette,
  Lightbulb,
  Search,
  Brain,
  Keyboard,
  Hand,
  Heart,
  Sparkles,
  Layers,
  Star,
  NotebookPen,
  FolderOpen,
  Target,
  UserRound,
  CircleCheck,
  BookOpen,
  CalendarDays,
  Hospital,
  PartyPopper,
  ShieldCheck,
  TriangleAlert,
  Trash2,
  SprayCan,
  Tag,
  Scale,
  Glasses,
  Ban,
  Recycle,
  ShowerHead,
  Wind,
  Archive,
  Flame,
  LockKeyhole,
  Thermometer,
  Megaphone,
  IdCard,
  UsersRound,
  Scissors,
  Droplets,
  Moon,
  Apple,
  Eye,
  HeartPulse,
  Handshake,
  PhoneOff,
  Coffee,
  PenLine,
  Utensils,
  AlarmClock,
  RefreshCw,
  Zap,
  Package,
  GraduationCap,
  Smile,
  Meh,
  Pause,
  Play,
  ArrowUpRight,
};
// Resolve older saved reminders without changing their text or storage format.
const legacyIcons = {
  '\u{1f451}': 'Crown',
  '\u{1f3a8}': 'Palette',
  '\u{1f4a1}': 'Lightbulb',
  '\u{1f50d}': 'Search',
  '\u{1f9e0}': 'Brain',
  '\u{2328}': 'Keyboard',
  '\u{1f44b}': 'Hand',
  '\u{2661}': 'Heart',
  '\u{2726}': 'Sparkles',
  '\u{2727}': 'Sparkles',
  '\u{2728}': 'Sparkles',
  '\u{1f5c2}': 'Layers',
  '\u{2b50}': 'Star',
  '\u{1f4d3}': 'NotebookPen',
  '\u{1f4c2}': 'FolderOpen',
  '\u{1f3af}': 'Target',
  '\u{1f464}': 'UserRound',
  '\u{2705}': 'CircleCheck',
  '\u{1f4da}': 'BookOpen',
  '\u{1f4c5}': 'CalendarDays',
  '\u{1f4dd}': 'NotebookPen',
  '\u{1f3e5}': 'Hospital',
  '\u{1f389}': 'PartyPopper',
  '\u{1f6e1}': 'ShieldCheck',
  '\u{1f9e4}': 'Hand',
  '\u{26a0}': 'TriangleAlert',
  '\u{1f5d1}': 'Trash2',
  '\u{1f9f4}': 'SprayCan',
  '\u{1f3f7}': 'Tag',
  '\u{2696}': 'Scale',
  '\u{1f97d}': 'Glasses',
  '\u{1f6ab}': 'Ban',
  '\u{267b}': 'Recycle',
  '\u{1f6bf}': 'ShowerHead',
  '\u{1f32c}': 'Wind',
  '\u{1f5c4}': 'Archive',
  '\u{1f525}': 'Flame',
  '\u{1f512}': 'LockKeyhole',
  '\u{1f637}': 'ShieldCheck',
  '\u{1f321}': 'Thermometer',
  '\u{1f4e2}': 'Megaphone',
  '\u{1faaa}': 'IdCard',
  '\u{1f465}': 'UsersRound',
  '\u{1f52a}': 'Scissors',
  '\u{2620}': 'TriangleAlert',
  '\u{1f4a7}': 'Droplets',
  '\u{1f634}': 'Moon',
  '\u{1f34e}': 'Apple',
  '\u{1f441}': 'Eye',
  '\u{1f9d8}': 'HeartPulse',
  '\u{1f91d}': 'Handshake',
  '\u{1f4f5}': 'PhoneOff',
  '\u{1f375}': 'Coffee',
  '\u{270d}': 'PenLine',
  '\u{1f373}': 'Utensils',
  '\u{23f0}': 'AlarmClock',
  '\u{1f504}': 'RefreshCw',
  '\u{1f58a}': 'PenLine',
  '\u{26a1}': 'Zap',
  '\u{1f4aa}': 'HeartPulse',
  '\u{1f4e6}': 'Package',
  '\u{1f393}': 'GraduationCap',
  '\u{1f510}': 'LockKeyhole',
  '\u{263a}': 'Smile',
  '\u{25e1}': 'Meh',
  '\u{263e}': 'Moon',
  '\u{23f8}': 'Pause',
  '\u{25b6}': 'Play',
  '\u{2197}': 'ArrowUpRight',
};
function resolveName(value) {
  return Object.hasOwn(icons, value)
    ? value
    : legacyIcons[String(value).replaceAll('\ufe0f', '')] || 'ShieldCheck';
}
export default function ThemedIcon({ name, size = 18, className = '', ...props }) {
  const Icon = icons[resolveName(name)];
  return (
    <Icon
      size={size}
      strokeWidth={1.8}
      aria-hidden="true"
      {...props}
      className={('themed-icon ' + className).trim()}
    />
  );
}
const choices = [
  'ShieldCheck',
  'TriangleAlert',
  'Hand',
  'Glasses',
  'Droplets',
  'Thermometer',
  'Tag',
  'Recycle',
];
export function SafetyIconPicker({ value, onChange, label }) {
  return (
    <div className="safety-icon-picker">
      <ThemedIcon name={value} size={20} />
      <select
        aria-label={label}
        value={choices.includes(resolveName(value)) ? resolveName(value) : ''}
        onChange={(e) => onChange(e.target.value)}
      >
        {!choices.includes(resolveName(value)) && <option value="">Current icon</option>}
        {choices.map((name) => (
          <option key={name} value={name}>
            {
              {
                ShieldCheck: 'Safety',
                TriangleAlert: 'Caution',
                Hand: 'Gloves',
                Glasses: 'Eye protection',
                Droplets: 'Fluids',
                Thermometer: 'Temperature',
                Tag: 'Labeling',
                Recycle: 'Disposal',
              }[name]
            }
          </option>
        ))}
      </select>
    </div>
  );
}
